Fix JSON to Object error
```
Caused by: com.brewerydb.api.exception.BreweryDBException:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException:
Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[INFO] 	at
com.brewerydb.api.BreweryDBClient.waitFor(BreweryDBClient.java:559)
[INFO] 	at
com.brewerydb.api.BreweryDBClient.getBeers(BreweryDBClient.java:112)
```